#' test script
#'
#' @file test.3-summarize-by-grade.R
#' @author Mariko Ohtsuka
#' @date 2021.11.25
rm(list=ls())
# ------ libraries ------
library(RUnit)
library(tidyverse)
library(here)
# ------ constants ------
kTestRawdataFileName <- 'dummyFA.csv'
kTestVisitFileName <- 'dummyVisit.csv'
kTestInputFileName <- 'extract-grade-observation.csv'
kTestTargetFileName <- 'summarize-by-grade.csv'
# ------ functions ------
ExecTest3 <- function(df1, df2, cond, cond2=NA, cond3=NA){
  df1 %>% write.table(here(test_dir, 'test2_extract-grade-observation.csv'), row.names=F, append=F, sep=',')
  exec_test <<- cond
  if (!is.na(cond2[1])){
    exec_test2 <<- cond2
  }
  if (!is.na(cond3[1])){
    exec_test3 <<- cond3
  }
  source(here('R', '3-summarize-by-grade.R'), encoding="utf-8")
  rm(exec_test, envir=.GlobalEnv)
  if (exists('exec_test2')){
    rm(exec_test2, envir=.GlobalEnv)
  }
  if (exists('exec_test3')){
    rm(exec_test3, envir=.GlobalEnv)
  }
  test_input <- ReadTargetCsv(test_dir, kTestTargetFileName)
  res <- checkEquals(test_input, df2) %>% print()
  error_f <- ifelse(!res, res, error_f)
  return(error_f)
}
# ------ init ------
print('*** test.summarize-by-grade start ***')
source(here('TEST', 'test.common.R'), encoding="utf-8")
test_dir = CreateTestFolder(here('test', 'temp'))
# ------ main ------
# run test
error_f <- T
# ### Test using anonymized rawdata ###
print('### Create a dummy file for testing. ###')
# source(here('TEST', 'test.inputfile-edit.R'), encoding="utf-8")
exec_test <- c(kInputFileName='dummy_extract-grade-observation.csv', dummy='')
source(here('R', '3-summarize-by-grade.R'), encoding="utf-8")
rm(exec_test)
test_input <- ReadTargetCsv(test_dir, kTestTargetFileName)
compare_input <- ReadTargetCsv(test_dir, 'compare_summarize-by-grade.csv')
res <- checkEquals(test_input, compare_input) %>% print()
error_f <- ifelse(!res, res, error_f)
print('### Worst grade. ###')
USUBJID <-  c('1', '1', '1', '2', '1', '1')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae0')
FAORRES <- c(1, 3, 4, 5, 0, 2)
VISITNUM <- c(100, 100, 100, 100, 101, 100)
VISIT <- c('test1', 'test1', 'test1', 'test1', 'test0', 'test1')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(100, 8), rep(101, 8))
VISIT <- c(rep('test1', 8), rep('test0', 8))
AETERM <- rep(c(rep('ae1', 4), rep('ae0', 4)), 2)
GRADE <- rep(c('3', '4', '5', '3-5'), 4)
N <- c(rep(2, 4), rep(1, 8), rep('-', 4))
COUNT <- c(0, 1, 1, 2, rep(0, 8), rep('-', 4))
PERCENT <- c(0, 50, 50, 100, rep(0, 8), rep('-', 4))
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(kInputFileName='test2_extract-grade-observation.csv', dummy=''), NA, NA)
print('### min visitnum. ###')
USUBJID <-  c('1', '1', '1', '2', '1', '1')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae0')
FAORRES <- c(1, 3, 4, 5, 0, 3)
VISITNUM <- c(100, 100, 101, 100, 101, 102)
VISIT <- c('test1', 'test1', 'test0', 'test1', 'test0', 'test2')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(101, 8), rep(102, 8))
VISIT <- c(rep('test0', 8), rep('test2', 8))
AETERM <- rep(c(rep('ae1', 4), rep('ae0', 4)), 2)
GRADE <- rep(c('3', '4', '5', '3-5'), 4)
N <- c(rep(1, 4), rep('-', 8), rep(1, 4))
COUNT <- c(0, 1, 0, 1, rep('-', 8), 1, 0, 0, 1)
PERCENT <- c(0, 100, 0, 100, rep('-', 8), 100, 0, 0, 100)
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(kMinVisitnum=101, kInputFileName='test2_extract-grade-observation.csv'), NA, NA)
print('### max visitnum. ###')
USUBJID <-  c('1', '1', '1', '2', '1', '1')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae0')
FAORRES <- c(1, 3, 4, 5, 0, 3)
VISITNUM <- c(100, 100, 101, 100, 101, 102)
VISIT <- c('test1', 'test1', 'test0', 'test1', 'test0', 'test2')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(100, 8), rep(101, 8))
VISIT <- c(rep('test1', 8), rep('test0', 8))
AETERM <- rep(c(rep('ae1', 4), rep('ae0', 4)), 2)
GRADE <- rep(c('3', '4', '5', '3-5'), 4)
N <- c(rep(2, 4), rep('-', 4), rep(1, 4), rep('-', 4))
COUNT <- c(1, 0, 1, 2, rep('-', 4), 0, 1, 0, 1, rep('-', 4))
PERCENT <- c(50, 0, 50, 100, rep('-', 4), 0, 100, 0, 100, rep('-', 4))
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(kMaxVisitnum=101, kInputFileName='test2_extract-grade-observation.csv'), NA, NA)
print('### exclude visitnum. ###')
USUBJID <-  c('1', '1', '1', '2', '1', '1')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae0')
FAORRES <- c(1, 3, 4, 5, 0, 3)
VISITNUM <- c(100, 100, 101, 100, 101, 102)
VISIT <- c('test1', 'test1', 'test0', 'test1', 'test0', 'test2')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(101, 8))
VISIT <- c(rep('test0', 8))
AETERM <- rep(c(rep('ae1', 4), rep('ae0', 4)), 1)
GRADE <- rep(c('3', '4', '5', '3-5'), 2)
N <- c(rep(1, 4), rep('-', 4))
COUNT <- c(0, 1, 0, 1, rep('-', 4))
PERCENT <- c(0, 100, 0, 100, rep('-', 4))
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(dummy='', kInputFileName='test2_extract-grade-observation.csv'), c(100, 102), NA)
print('### target grade. ###')
USUBJID <-  c('1', '1', '1', '2', '1', '1')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae0')
FAORRES <- c(1, 3, 4, 5, 0, 3)
VISITNUM <- c(100, 100, 101, 100, 101, 102)
VISIT <- c('test1', 'test1', 'test0', 'test1', 'test0', 'test2')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(100, 6), rep(101, 6), rep(102, 6))
VISIT <- c(rep('test1', 6), rep('test0', 6), rep('test2', 6))
AETERM <- rep(c(rep('ae1', 3), rep('ae0', 3)), 3)
GRADE <- rep(c('4', '5', '4-5'), 6)
N <- c(rep(2, 3), rep('-', 3), rep(1, 3), rep('-', 6), rep(1, 3))
COUNT <- c(0, 1, 1, rep('-', 3), 1, 0, 1, rep('-', 6), 0, 0, 0)
PERCENT <- c(0, 50, 50, rep('-', 3), 100, 0, 100, rep('-', 6), 0, 0, 0)
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(dummy='', kInputFileName='test2_extract-grade-observation.csv'), NA, c(4, 5))
print('### percent digit. ###')
USUBJID <-  c('1', '2', '3', '4', '5', '6')
FAOBJ <- c('ae1', 'ae1', 'ae1', 'ae1', 'ae1', 'ae1')
FAORRES <- c(0, 3, 4, 5, 3, 3)
VISITNUM <- c(100, 100, 100, 100, 100, 100)
VISIT <- c('test1', 'test1', 'test1', 'test1', 'test1', 'test1')
df <- data.frame(USUBJID, FAOBJ, FAORRES, VISITNUM, VISIT)
VISITNUM <- c(rep(100, 4))
VISIT <- c(rep('test1', 4))
AETERM <- rep('ae1', 4)
GRADE <- rep(c('3', '4', '5', '3-5'), 1)
N <- rep(6, 4)
COUNT <- c(3, 1, 1, 5)
PERCENT <- c(50, 16.67, 16.67, 83.33)
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(kPercentDigit=2, kInputFileName='test2_extract-grade-observation.csv'), NA, NA)
PERCENT <- c(50, 17, 17, 83)
compare_input <- data.frame(VISITNUM, VISIT, AETERM, GRADE, N, COUNT, PERCENT)
error_f <- ExecTest3(df, compare_input, c(kPercentDigit=0, kInputFileName='test2_extract-grade-observation.csv'), NA, NA)
PrintOverallResults(error_f)
print('*** test.summarize-by-grade end ***')
